version: '3.8'

services:
  redis:
    build: ./app/redis
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/opt/redis

  web:
    build: ./app/web
    ports:
      - "5055:5055"
      - "5005:5005"
      - "5006:5006"
      - "5002:5002"
      - "5000:5000"
      - "8888:8888"
      - "7000:7000"
      - "3000-3090:3000-3090" # Adjust the range as needed
    depends_on:
      - duckling 
      - redis  
    volumes:
      - web_data:/web

  mydb:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mypwd
      - POSTGRES_USER=myusr
    ports:
      - "8069:8069"  

  duckling:
    image: rasa/duckling
    ports:
      - "8000:8000"  

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  redis_data:
  web_data:
